server:
  port: 8001

spring:
  application:
    name: client1

eureka:
  client:
    security:
      basic:
        user: admin
        password: 123456
    serviceUrl:
      defaultZone: http://${eureka.client.security.basic.user}:${eureka.client.security.basic.password}@localhost:8761/eureka/